load("//:civ_build.bzl", "civ_plugin_jar")

civ_plugin_jar(
    name = "ExilePearl",
    deps = [
      "//Spigot:Spigot",
      "//CivModCore:CivModCore",
      "//NameLayer:NameLayer",
	  "//Citadel:Citadel",
	  "//CivChat2:CivChat2",
	  "//WorldBorder:WorldBorder",
	  "//CombatTagPlus:CombatTagPlus",
	  "//BanStick:BanStick",
	  "//RandomSpawn:RandomSpawn",
    ],
)
