load("//:civ_build.bzl", "civ_plugin_jar")

civ_plugin_jar(
    name = "Citadel",
    version = "4.2.0",
    deps = [
      "//Spigot:Spigot",
      "//CivModCore:CivModCore",
      "//NameLayer:NameLayer",
      "@maven//:com_gmail_filoghost_holographicdisplays_holographicdisplays_api",
    ],
)
