load("//:civ_build.bzl", "civ_plugin_jar")

civ_plugin_jar(
    name = "JukeAlert",
    version = "2.1.0",
    deps = [
      "//Spigot:Spigot",
      "//CivModCore:CivModCore",
      "//Citadel:Citadel",
      "//NameLayer:NameLayer",
      "//VanishNoPacket:VanishNoPacket",
    ],
)
