biome_image: biomes.png
height_image: heightmap.png
sea_level: 35
ground_padding: 4

biomes:
  PLAINS:
    fine: 0.0
    hill: 0.2
    broad: 0.6
  TAIGA:
    fine: 1.0
    hill: 1.0
    broad: 0.6
  SWAMP:
    fine: 0.5
    hill: 0.0
    broad: 1.0
  FOREST:
    fine: 1.0
    hill: 1.0
    broad: 1.0
  MOUNTAINS:
    fine: 1.5
    hill: 1.5
    broad: 1.5
  SAVANNA:
    fine: 0.0
    hill: 0.2
    broad: 0.6
  DESERT:
    fine: 0.0
    hill: 0.2
    broad: 0.6
    topblock: SAND
  JUNGLE:
    fine: 1.0
    hill: 1.2
    broad: 0.6
  MUSHROOM_FIELDS:
    fine: 0.0
    hill: 0.2
    broad: 0.6
    topblock: MYCELIUM
  DARK_FOREST:
    fine: 1.0
    hill: 1.0
    broad: 1.0
  OCEAN:
    fine: 0.0
    hill: 0.2
    broad: 0.0
    topblock: CLAY
  MESA:
    fine: 0
    hill: 0.1
    brod: 0.1
    topblock: HARDENED_CLAY

biome_centers:
  a:
    type: PLAINS
    radius: 500
    x: 4000
    z: 2500
    height: 90
  b:
    type: TAIGA
    radius: 500
    x: 4000
    z: 3000
    height: 130
  c:
    type: MUSHROOM_FIELDS
    radius: 150
    x: 1000
    z: 4000
    height: 100
