biome_image: biomes.png
height_image: heightmap.png
sea_level: 40
ground_padding: 4

biomes:
  PLAINS:
    color: '#ff9a00'
  TAIGA:
    color: '#31ff00'
  SWAMP:
    color: '#31ff00'
  FOREST:
    color: '#00ff80'
  MOUNTAINS:
    color: '#00ffec'
  SAVANNA:
    color: '#ffd700'
  DESERT:
    color: '#eeff00'
    topblock: SAND
  JUNGLE:
    color: '#ff008a'
  MUSHROOM_FIELDS:
    color: '#da00ff'
    topblock: MYCELIUM
  DARK_FOREST:
    color: '#8d00ff'
  OCEAN:
    color: '#1200ff'
    topblock: CLAY
