load("//:civ_build.bzl", "civ_plugin_jar")

civ_plugin_jar(
    name = "FactoryMod",
    deps = [
      "//Spigot:Spigot",
      "//CivModCore:CivModCore",
      "//NameLayer:NameLayer",
	  "//Citadel:Citadel",
    ],
)
