load("//:civ_build.bzl", "civ_plugin_jar")

civ_plugin_jar(
    name = "RandomSpawn",
    version = "2.9.0",
    deps = [
      "//Spigot:Spigot",
      "//CivModCore:CivModCore",
      "//WorldBorder:WorldBorder",
    ],
)
