load("//:civ_build.bzl", "civ_plugin_jar")

civ_plugin_jar(
    name = "Finale",
    deps = [
      "//Spigot:Spigot",
      "//CivModCore:CivModCore",
	  "//CombatTagPlus:CombatTagPlus",
      "@maven//:com_comphenix_protocol_ProtocolLib",
    ],
)
