load("//:civ_build.bzl", "civ_plugin_jar")

civ_plugin_jar(
    name = "Bastion",
    version = "2.4.0",
    deps = [
      "//Spigot:Spigot",
      "//CivModCore:CivModCore",
      "//NameLayer:NameLayer",
      "//Citadel:Citadel",
    ],
)
