load("//:civ_build.bzl", "civ_plugin_jar")

civ_plugin_jar(
    name = "WordBank",
    deps = [
      "//Spigot:Spigot",
      "@maven//:com_zaxxer_HikariCP",
      "@maven//:org_mockito_mockito_core",
    ],
)
