load("//:civ_build.bzl", "civ_plugin_jar")

civ_plugin_jar(
    name = "CombatTagPlus",
    deps = [
      "//Spigot:Spigot",
      "@maven//:me_confuser_BarAPI",
      "@maven//:com_connorlinfoot_ActionBarAPI",
      "@maven//:org_inventivetalent_BossBarAPI",
    ],
)
