load("//:civ_build.bzl", "civ_plugin_jar")

civ_plugin_jar(
    name = "WorldBorder",
    deps = [
      "//Spigot:Spigot",
      "@maven//:us_dynmap_dynmap_api",
      "@maven//:io_papermc_paperlib",
    ],
)
