load("//:civ_build.bzl", "civ_plugin_kt_jar")

civ_plugin_kt_jar(
    name = "VorpalSword",
    version = "1.0.0",
    deps = [
        "//CivModCore",
        "//CombatTagPlus",
        "//NameLayer",
        "//RandomSpawn",
        "//Spigot",
    ],
)
