load("//:civ_build.bzl", "civ_plugin_kt_jar")

civ_plugin_kt_jar(
    name = "VorpalSword",
    deps = [
        "//CivModCore",
        "//CombatTagPlus",
        "//NameLayer",
        "//RandomSpawn",
        "//Spigot",
    ],
)
