# Allow for locked-in custom names derived from colors and word list

configuration_file_version: 1

wordlist_file: words.txt
activation_length: 10
activate_any_length: true
padding: 'â'
add_serial: false
makers_mark: "Marked Item"
debug: false
db:
  driver: mysql
  host: localhost
  name: wordbank
  port: 3306
  user: root
  password: ''
cost:
  ==: org.bukkit.inventory.ItemStack
  type: EXPERIENCE_BOTTLE
  v: 1
  amount: 10
color:
  chars: [9, 9]
  function: com.programmerdan.minecraft.wordbank.functions.NormalDistribution
  function_terms:
  - SHA-1
word:
  max: 3
  count:
    chars: [1, 4]
    function: com.programmerdan.minecraft.wordbank.functions.Modulus
    function_terms:
    - 3 
  0:
    chars: [0, 2, 3, 9]
    function: com.programmerdan.minecraft.wordbank.functions.HashMap
    function_terms:
    - MD5
  1:
    chars: [1, 3, 4, 8]
    function: com.programmerdan.minecraft.wordbank.functions.HashMap
    function_terms:
    - MD5
  2:
    chars: [2, 5, 6, 7]
    function: com.programmerdan.minecraft.wordbank.functions.HashMap
    function_terms:
    - MD5
