#database:
#  ==: vg.civcraft.mc.civmodcore.dao.ManagedDatasource
#  plugin: JukeAlert
#  user: username
#  password: squidLover69
#  host: localhost
#  port: 3306
#  database: snitches
#  poolsize: 5
#  connection_timeout: 10000
#  idle_timeout: 600000
#  max_lifetime: 7200000

snitchConfigs:
  juke:
    item: 
      ==: org.bukkit.inventory.ItemStack
      type: JUKEBOX
    range: 10
    softDeleteTimer: 2 weeks
    lifeTime: 1 month
    dormantTime: 2 months
    displayOwnerOnBreak: true
    triggerLevers: true