#Log when a player forcefully breaks reinforcements?
logHostileBreaks: true

#Log when a player bypasses friendly reinforcements?
logFriendlyBreaks: true

#Log every time damage is done to a reinforcement? Only recommended for debugging        
logDamage: true

#Log creation of reinforcements?
logCreation: true

#Log message replies sent to users? Very useful
logMessages: true

#General debug messages
debug: true

reinforcements:
  stone:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: STONE
    effect:
      type: ENCHANTMENT_TABLE
      speed: 0.5
      particleCount: 50
    mature_time: 5m
    acid_time: 20m
    name: Stone
    hit_points: 50
    id: 1
  iron:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: IRON_INGOT
    effect:
      type: ENCHANTMENT_TABLE
      speed: 0.5
      particleCount: 50
    mature_time: 30m
    acid_time: 6h
    name: Iron
    hit_points: 300
    id: 2
  diamond:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: DIAMOND
    effect:
      type: ENCHANTMENT_TABLE
      speed: 0.5
      particleCount: 50
    mature_time: 4h
    acid_time: 48h
    name: Diamond
    hit_points: 2000
    id: 3
  bedrock:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: BEDROCK
    effect:
      type: ENCHANTMENT_TABLE
      speed: 0.5
      particleCount: 50
    mature_time: 1s
    acid_time: 1s
    name: Bedrock
    hit_points: 420420420
    id: 4
    
non_reinforceables:
 - BEDROCK
 - END_PORTAL_FRAME
 - ACACIA_SAPLING
 - BAMBOO_SAPLING
 - BIRCH_SAPLING
 - DARK_OAK_SAPLING
 - JUNGLE_SAPLING
 - OAK_SAPLING
 - SPRUCE_SAPLING
 - TALL_GRASS
 - DEAD_BUSH
 - MOVING_PISTON
 - PISTON_HEAD
 - POPPY
 - DANDELION
 - BROWN_MUSHROOM
 - RED_MUSHROOM
 - TNT
 - FIRE
 - SNOW
 - ICE
 - CACTUS
 - SUGAR_CANE
 - NETHER_PORTAL
 - END_PORTAL
 - CAKE
 - PUMPKIN_STEM
 - MELON_STEM
 - VINE
 - NETHER_WART
 
acidblock_material:
 - GOLD_BLOCK

# Determines whether hanging entities (such as Item Frames) can be protected by their host block
hangers_inherit_reinforcement: false

# reinforcement_damageMultiplier is m where BlockDamage = 2 ^ (n/m) where n is equal to the number of days the group has been inactive
reinforcement_damageMultiplier: 365
#database:
#  ==: vg.civcraft.mc.civmodcore.dao.ManagedDatasource
#  plugin: Citadel
#  user: username
#  password: squidLover69
#  host: localhost
#  port: 3306
#  database: citadel
#  poolsize: 5
#  connection_timeout: 10000
#  idle_timeout: 600000
#  max_lifetime: 7200000  
