name: ${project.name}
main: vg.civcraft.mc.citadel.Citadel
version: ${project.version}
authors:
- Rourke750
- Maxopoly
- ProgrammerDan
- okx-code
- Cranite
- FeatherCrown
- Lazersmoke
- TealNerd
depend:
- NameLayer
- CivModCore
softdepend:
- HolographicDisplays
description: Citadel allows you to make blocks difficult to break. When a block is reinforced, it must be broken many times before it is destroyed.
commands:
  ctr:
    aliases:
    - ctreinforce
    - reinforce
    - protect
    - cprivate
    - lwc
    - private
    usage: /ctr [group]
    description: Enters reinforcing mode. Interacting with blocks in reinforcing mode will reinforce them or modify their reinforcement
    min-args: 0
    max-args: 1
    player-only: true
  ctacid:
    usage: /ctacid
    description: Removes the block above it if used on an acid block
    min-args: 0
    max-args: 0
    player-only: true
  ctf:
    aliases:
    - ctfortify
    - fortify
    usage: /ctf [group]
    description: Enters fortification mode. All blocks placed in fortification mode will automatically be reinforced. If no group is given, your default group will be used
    min-args: 0
    max-args: 1
    player-only: true
  ctb:
    aliases:
    - ctbypass
    - bypass
    usage: /ctb
    description: Toggles bypass state. In bypass state you can break blocks reinforced on groups you have access to in a single break
    min-args: 0
    max-args: 0
    player-only: true
  cti:
    aliases:
    - ctinformation
    - info
    - ctinfo
    usage: /cti
    description: Enters information mode. Interacting with blocks in information mode will show information on their reinforcement
    min-args: 0
    max-args: 0
    player-only: true
  ctin:
    aliases:
    - ctinsecure
    - insecure
    usage: /ctin
    description: Enters insecure mode. Interacting with containers in insecure mode will switch their insecure flag. Insecure containers can interact with hoppers reinforced on a different group. All containers are secure by default
    min-args: 0
    max-args: 0
    player-only: true
  cto:
    aliases:
    - ctoff
    - false
    usage: /cto
    description: Leaves all reinforcement modes
    min-args: 0
    max-args: 0
    player-only: true
  ctur:
    permission: citadel.admin
    player-only: true
  ctar:
    permission: citadel.admin
    aliases:
    - ctareareinforce
    player-only: true
  cte:
    aliases:
    - cteasy
    - toggleeasymode
    player-only: true
  ctdl:
    aliases:
    - reinforcements
    - rein
    usage: /ctdl
    description: Opens a GUI displaying all reinforcement materials
    min-args: 0
    max-args: 0
    player-only: true
  citadelreload:
    aliases:
    - reloadcitadel
    usage: /citadelreload
    description: Reloads Citadel entirely
    min-args: 0
    max-args: 0
    permission: citadel.admin
  ctp:
    aliases:
    - repair
    - patch
    - ctrepair
    - ctpatch
    usage: /ctp
    min-args: 0
    max-args: 0
    player-only: true
    description: Enters patch mode, which allows you to repair reinforcements. Note that repairing reinforcements will also reset their maturation cycle
  cta:
    usage: /cta [group]
    description: Enters advanced fortification mode or adds configurations to it. Advanced configuration mode allows you to place on different groups with different reinforcement types at once
    min-args: 0
    max-args: 1
    player-only: true
permissions:
  citadel.admin:
    default: op
api-version: 1.14
