load("//:civ_build.bzl", "civ_plugin_jar")

civ_plugin_jar(
    name = "CivChat2",
    deps = [
      "//Spigot:Spigot",
      "//CivModCore:CivModCore",
      "//NameLayer:NameLayer",
      "@maven//:org_apache_logging_log4j_log4j_core",
    ],
)
