load("//:civ_build.bzl", "civ_plugin_jar")

civ_plugin_jar(
    name = "BanStick",
    deps = [
      "//Spigot:Spigot",
      "//CivModCore:CivModCore",
      "//NameLayer:NameLayer",
      "@maven//:com_github_seancfoley_ipaddress",
      "@maven//:org_jsoup_jsoup",
    ],
)
